title: Taha Mirghorbani
logo: assets/photo_2024-07-17_21-48-58-modified.png
description: My name is Taha Mirghorbani, and I am a Lundquist College of Business graduate who is currently pursuing a Masters of Science in Applied Statistics at Loyola University Chicago college of Math and Statistics with a research emphasis on data visualization and Generative Ai. 
#show_downloads: true
theme: jekyll-theme-minimal
author:
  name : Taha
  email: tmirghorbani@luc.edu
  linkedin: mirghorbani-t

