title: Taha Mirghorbani
logo: assets/photo_2024-07-17_21-48-58-modified.png
description: My name is Taha Mir, a recent graduate of the MS in Applied Statistics program at Loyola University Chicago, with a B.Sc. in Operations and Business Analytics from the Lundquist College of Business. My research focuses on Human-Computer Interaction and Generative AI, combining data-driven insights with innovative technologies to enhance human-machine collaboration.
#show_downloads: true
theme: jekyll-theme-minimal
author:
  name : Taha
  email: tmirghorbani@luc.edu
  linkedin: mirghorbani-t

